# Generated by Django 5.0.6 on 2024-05-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vata', '0002_alter_types_options_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='description',
        ),
        migrations.AddField(
            model_name='movie',
            name='types',
            field=models.ManyToManyField(to='vata.types', verbose_name='Тип контента'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='posters/%Y', verbose_name='Постер'),
        ),
    ]
