# Generated by Django 5.0.6 on 2024-05-28 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vata', '0003_remove_genre_description_movie_types_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('text_comments', models.CharField(max_length=400, verbose_name='Текс комментария')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vata.movie', verbose_name='Фильм')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
