# Generated by Django 5.0.6 on 2024-05-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vata', '0004_addcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcomments',
            name='text_comments',
            field=models.CharField(max_length=400, verbose_name='Текст комментария'),
        ),
    ]
